@extends('layouts.app')

@section('title', 'Invoices Register')

@section('content')
<div class="space-y-6">
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
            <h1 class="text-2xl font-bold text-slate-900 tracking-tight">Invoices & Receipts</h1>
            <p class="text-sm text-slate-500">Official tax invoices and customer payment receipts generated by the restaurant POS.</p>
        </div>
        <a href="{{ route('pos.index') }}" class="inline-flex items-center gap-2 px-3.5 py-2 text-xs font-bold rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white shadow-sm transition">
            <i data-lucide="plus" class="w-4 h-4"></i>
            <span>New Sale</span>
        </a>
    </div>

    <!-- Search -->
    <div class="bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
        <form method="GET" action="{{ route('invoices.index') }}" class="flex gap-3">
            <div class="relative flex-1">
                <i data-lucide="search" class="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2"></i>
                <input type="text" name="search" value="{{ request('search') }}" placeholder="Search by invoice number or customer name..."
                       class="w-full pl-9 pr-3 py-2 text-xs border border-slate-300 rounded-lg focus:ring-1 focus:ring-emerald-500">
            </div>
            <button type="submit" class="py-2 px-4 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg text-xs font-semibold">
                Search
            </button>
            @if(request('search'))
            <a href="{{ route('invoices.index') }}" class="py-2 px-3 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-lg text-xs font-semibold">
                Reset
            </a>
            @endif
        </form>
    </div>

    <!-- Invoices Table -->
    <div class="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        <div class="overflow-x-auto">
            <table class="w-full text-left text-xs text-slate-600">
                <thead class="bg-slate-50 text-slate-700 font-semibold uppercase tracking-wider border-b border-slate-200">
                    <tr>
                        <th class="py-3 px-4">Invoice #</th>
                        <th class="py-3 px-4">Date & Time (NPT)</th>
                        <th class="py-3 px-4">Customer</th>
                        <th class="py-3 px-4">Cashier</th>
                        <th class="py-3 px-4">Payment Method</th>
                        <th class="py-3 px-4 text-right">Grand Total (NPR)</th>
                        <th class="py-3 px-4 text-center">Status</th>
                        <th class="py-3 px-4 text-right">Print Actions</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-100">
                    @forelse($invoices as $invoice)
                    <tr class="hover:bg-slate-50/70 transition">
                        <td class="py-3 px-4 font-mono font-bold text-slate-900">
                            {{ $invoice->invoice_number }}
                        </td>
                        <td class="py-3 px-4 font-mono text-slate-500 whitespace-nowrap">
                            {{ $invoice->created_at->setTimezone('Asia/Kathmandu')->format('M d, Y h:i A') }}
                        </td>
                        <td class="py-3 px-4 font-medium text-slate-800">
                            {{ $invoice->customer_name }}
                        </td>
                        <td class="py-3 px-4 text-slate-500">
                            {{ $invoice->cashier_name }}
                        </td>
                        <td class="py-3 px-4">
                            <span class="px-2 py-0.5 rounded text-[10px] font-semibold bg-slate-100 text-slate-700">
                                {{ $invoice->payment_method }}
                            </span>
                        </td>
                        <td class="py-3 px-4 text-right font-mono font-bold text-slate-900 text-sm">
                            {{ format_npr($invoice->grand_total) }}
                        </td>
                        <td class="py-3 px-4 text-center">
                            <span class="px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 text-emerald-800">
                                {{ $invoice->payment_status }}
                            </span>
                        </td>
                        <td class="py-3 px-4 text-right whitespace-nowrap">
                            <div class="flex items-center justify-end gap-2">
                                <a href="{{ route('invoices.show', $invoice->id) }}" class="px-2.5 py-1 rounded bg-slate-100 hover:bg-slate-200 text-slate-700 font-semibold text-[11px]">
                                    View
                                </a>
                                <a href="{{ route('invoices.receipt', $invoice->id) }}" target="_blank" class="px-2.5 py-1 rounded bg-emerald-600 hover:bg-emerald-700 text-white font-semibold text-[11px] flex items-center gap-1">
                                    <i data-lucide="printer" class="w-3.5 h-3.5"></i>
                                    <span>Receipt</span>
                                </a>
                                @if(auth()->user()->isAdmin())
                                <form action="{{ route('invoices.destroy', $invoice->id) }}" method="POST" class="inline"
                                      onsubmit="return confirm('Delete invoice {{ $invoice->invoice_number }}? The linked sale, its line items and payments will also be permanently removed. This cannot be undone.');">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="p-1.5 rounded text-rose-500 hover:bg-rose-50" title="Permanently delete invoice (admin only)">
                                        <i data-lucide="trash-2" class="w-3.5 h-3.5"></i>
                                    </button>
                                </form>
                                @endif
                            </div>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="8" class="py-12 text-center text-slate-400">
                            No invoices generated yet.
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

        @if($invoices->hasPages())
        <div class="p-4 border-t border-slate-200 bg-slate-50">
            {{ $invoices->links() }}
        </div>
        @endif
    </div>
</div>
@endsection
